/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.controladorPrincipal;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.vo.Socio;

/**
 *
 * @author Acceso a datos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Enunciado1
     */
    public Principal() {
        initComponents();
        controladorPrincipal.iniciarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreSocio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaAlta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCuotaSocio = new javax.swing.JTextField();
        btnInsertarSocio = new javax.swing.JButton();
        btnModificarSocio = new javax.swing.JButton();
        btnBorrarSocio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNombreActividad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechaActividad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDuracionActividad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtProfesorActividad = new javax.swing.JTextField();
        btnInsertarActividad = new javax.swing.JButton();
        btnBorrarActividad = new javax.swing.JButton();
        cbTipoActividad = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        cbUsuarioActividad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("nombre");

        txtNombreSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreSocioFocusLost(evt);
            }
        });
        txtNombreSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSocioActionPerformed(evt);
            }
        });

        jLabel2.setText("dni");

        txtDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDniFocusLost(evt);
            }
        });
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        jLabel3.setText("fecha alta");

        jLabel4.setText("cuota");

        btnInsertarSocio.setText("Insertar");
        btnInsertarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarSocioActionPerformed(evt);
            }
        });

        btnModificarSocio.setText("Modificar");
        btnModificarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarSocioActionPerformed(evt);
            }
        });

        btnBorrarSocio.setText("Borrar");
        btnBorrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarSocioActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre actividad");

        jLabel6.setText("tipo");

        jLabel7.setText("fecha");

        jLabel8.setText("duracion");

        jLabel9.setText("Profesor");

        btnInsertarActividad.setText("Insertar");
        btnInsertarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActividadActionPerformed(evt);
            }
        });

        btnBorrarActividad.setText("Borrar");
        btnBorrarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActividadActionPerformed(evt);
            }
        });

        cbTipoActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        cbUsuarioActividad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUsuarioActividadItemStateChanged(evt);
            }
        });
        cbUsuarioActividad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbUsuarioActividadFocusLost(evt);
            }
        });
        cbUsuarioActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUsuarioActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cbTipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbUsuarioActividad, javax.swing.GroupLayout.Alignment.LEADING, 0, 148, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNombreActividad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreSocio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDni, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaAlta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCuotaSocio, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDuracionActividad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(txtProfesorActividad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaActividad, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertarSocio)
                            .addComponent(btnModificarSocio)
                            .addComponent(btnBorrarSocio)
                            .addComponent(btnInsertarActividad)
                            .addComponent(btnBorrarActividad))))
                .addContainerGap(596, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarSocio))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarSocio))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarSocio))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCuotaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(cbUsuarioActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(cbTipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertarActividad)
                        .addGap(103, 103, 103)
                        .addComponent(btnBorrarActividad)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDuracionActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProfesorActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controladorPrincipal.cerrarConexion();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        controladorPrincipal.cargarCombo();
    }//GEN-LAST:event_formWindowOpened

    private void txtNombreSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSocioActionPerformed

    private void txtNombreSocioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreSocioFocusLost
        
    }//GEN-LAST:event_txtNombreSocioFocusLost

    private void btnInsertarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarSocioActionPerformed
        controladorPrincipal.insertarSocio();
       controladorPrincipal.cargarCombo();
    }//GEN-LAST:event_btnInsertarSocioActionPerformed

    private void btnModificarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarSocioActionPerformed

    private void btnBorrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarSocioActionPerformed

    private void btnInsertarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActividadActionPerformed
        controladorPrincipal.insertarActividad();
    }//GEN-LAST:event_btnInsertarActividadActionPerformed

    private void btnBorrarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActividadActionPerformed

    private void cbUsuarioActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUsuarioActividadActionPerformed
         controladorPrincipal.cargarSocio();
    }//GEN-LAST:event_cbUsuarioActividadActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDniFocusLost
      controladorPrincipal.buscarSocio();
    }//GEN-LAST:event_txtDniFocusLost

    private void cbUsuarioActividadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUsuarioActividadItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUsuarioActividadItemStateChanged

    private void cbUsuarioActividadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbUsuarioActividadFocusLost
       
    }//GEN-LAST:event_cbUsuarioActividadFocusLost

    public JButton getBtnBorrarActividad() {
        return btnBorrarActividad;
    }

    public void setBtnBorrarActividad(JButton btnBorrarActividad) {
        this.btnBorrarActividad = btnBorrarActividad;
    }

    public JButton getBtnBorrarSocio() {
        return btnBorrarSocio;
    }

    public void setBtnBorrarSocio(JButton btnBorrarSocio) {
        this.btnBorrarSocio = btnBorrarSocio;
    }

    public JButton getBtnInsertarActividad() {
        return btnInsertarActividad;
    }

    public void setBtnInsertarActividad(JButton btnInsertarActividad) {
        this.btnInsertarActividad = btnInsertarActividad;
    }

    public JButton getBtnInsertarSocio() {
        return btnInsertarSocio;
    }

    public void setBtnInsertarSocio(JButton btnInsertarSocio) {
        this.btnInsertarSocio = btnInsertarSocio;
    }

    public JButton getBtnModificarSocio() {
        return btnModificarSocio;
    }

    public void setBtnModificarSocio(JButton btnModificarSocio) {
        this.btnModificarSocio = btnModificarSocio;
    }

    public JComboBox<String> getCbTipoActividad() {
        return cbTipoActividad;
    }

    public void setCbTipoActividad(JComboBox<String> cbTipoActividad) {
        this.cbTipoActividad = cbTipoActividad;
    }

    public JComboBox<Socio> getCbUsuarioActividad() {
        return cbUsuarioActividad;
    }

    public void setCbUsuarioActividad(JComboBox<Socio> cbUsuarioActividad) {
        this.cbUsuarioActividad = cbUsuarioActividad;
    }

    public JTextField getTxtCuotaSocio() {
        return txtCuotaSocio;
    }

    public void setTxtCuotaSocio(JTextField txtCuotaSocio) {
        this.txtCuotaSocio = txtCuotaSocio;
    }

    public JTextField getTxtDni() {
        return txtDni;
    }

    public void setTxtDni(JTextField txtDni) {
        this.txtDni = txtDni;
    }

    public JTextField getTxtDuracionActividad() {
        return txtDuracionActividad;
    }

    public void setTxtDuracionActividad(JTextField txtDuracionActividad) {
        this.txtDuracionActividad = txtDuracionActividad;
    }

    public JTextField getTxtFechaAlta() {
        return txtFechaAlta;
    }

    public void setTxtFechaAlta(JTextField txtFechaAlta) {
        this.txtFechaAlta = txtFechaAlta;
    }

    public JTextField getTxtFechaActividad() {
        return txtFechaActividad;
    }

    public void setTxtFechaActividad(JTextField txtFechaActividad) {
        this.txtFechaActividad = txtFechaActividad;
    }

    public JTextField getTxtNombreActividad() {
        return txtNombreActividad;
    }

    public void setTxtNombreActividad(JTextField txtNombreActividad) {
        this.txtNombreActividad = txtNombreActividad;
    }

  

    public JTextField getTxtNombreSocio() {
        return txtNombreSocio;
    }

    public void setTxtNombreSocio(JTextField txtNombreSocio) {
        this.txtNombreSocio = txtNombreSocio;
    }

    public JTextField getTxtProfesorActividad() {
        return txtProfesorActividad;
    }

    public void setTxtProfesorActividad(JTextField txtProfesorActividad) {
        this.txtProfesorActividad = txtProfesorActividad;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarActividad;
    private javax.swing.JButton btnBorrarSocio;
    private javax.swing.JButton btnInsertarActividad;
    private javax.swing.JButton btnInsertarSocio;
    private javax.swing.JButton btnModificarSocio;
    private javax.swing.JComboBox<String> cbTipoActividad;
    private javax.swing.JComboBox<Socio> cbUsuarioActividad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCuotaSocio;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDuracionActividad;
    private javax.swing.JTextField txtFechaActividad;
    private javax.swing.JTextField txtFechaAlta;
    private javax.swing.JTextField txtNombreActividad;
    private javax.swing.JTextField txtNombreSocio;
    private javax.swing.JTextField txtProfesorActividad;
    // End of variables declaration//GEN-END:variables
}
